### ISSUE TITLE
Dynamic_pipeline_options should allow to specify format.

### ISSUE THREAD

**Issue by szewi** [GoogleCloudPlatform/PerfKitBenchmarker#1555]
This will be very useful for performance testing of hadoop clusters and any other tests where complex options are needed. Format will define pattern that will be used to create final option. In example: ` hdfsConfiguration` option will be created by substitution `LoadBalancerIp` in pattern.

```
 static_pipeline_options:
 dynamic_pipeline_options:
  - name: hdfsConfiguration
    format: '[{\"fs.defaultFS\":\"hdfs://{{LoadBalancerIp}}:9000\",\"dfs.replication\":1}]'
    type: LoadBalancerIp
    serviceName: hadoop-external
```
