### ISSUE TITLE
Incorrect Python package names for RHEL on AWS

### ISSUE THREAD

**Issue by HarpPDX** [GoogleCloudPlatform/PerfKitBenchmarker#1867]
RhelBasedAwsVirtualMachine class in aws_virtual_machine.py specifies 'python27', 'python27-dev', and 'python27-pip'.  

Should be 'python', 'python2-devel', and 'python2-pip'.

Tested on AWS, us-west-2, with RHEL 7.6 ('ami-036affea69a1101c9').

**Comment by s-deitz** [comment]
Thanks for opening this issue. If you'd like to send a PR to fix it, we can get that in.

Out of curiosity, when did you run into this? Did you use the flags --os_type=rhel and --cloud=AWS? What benchmark?

**Comment by HarpPDX** [comment]
@s-deitz I'm not able to submit a PR (don't yet have permission to sign a CLA).  Please see benchmark configuration below. Was able to reproduce the problem, and verify the fix, today.

```
skl_worker: &skl_worker
  AWS:
    machine_type: m5.4xlarge
    zone: us-west-2

worker_disk: &worker_disk
  AWS:
    disk_type: standard
    disk_size: 200
    mount_point: /scratch

fio:
  vm_groups:
    default:
      os_type: rhel
      vm_spec: *skl_worker
      disk_spec: *worker_disk

flags:
  image: 'ami-036affea69a1101c9' # RedHat 7.6
```
