### ISSUE TITLE
Q: How is an on-prem/pre-existing K8S cluster specified in the benchmark config?

### ISSUE THREAD

**Issue by HarpPDX** [GoogleCloudPlatform/PerfKitBenchmarker#2578]
To provision a K8S cluster on Cloud, I can do this:

```
my_benchmark:
  vm_groups:
    client:
      vm_spec: *default_dual_core
  container_cluster:
    vm_spec: *default_dual_core
```

If I want to use a local, pre-existing, K8S cluster I cannot figure out how to create the spec in a way that PKB knows that it doesn't need to provision the cluster. I can use 'static_vms' for vm_groups, but can't find something similar for container_cluster.

```
...
my_benchmark:
  vm_groups:
    client:
      static_vms:
        - *a_local_machine
  container_cluster:
      ???????
```
