### ISSUE TITLE
Getting error: "The key was not in the default config, but was in user overrides".This may indicate a typo

### ISSUE THREAD

**Issue by sgangaraju** [GoogleCloudPlatform/PerfKitBenchmarker#799]
I am trying to run iperf tests on already provisioned Vms  in openstack based cloud.I followed the instructions in  section "Advanced: How To Run Benchmarks Without Cloud Provisioning (e.g., local workstation) " in PerfKitBenchmarker Wiki and created a user config file sai_user_config.yaml under PerfKitBenchmarker/perfkitbenchmarker/configs dir that looks as follows which has the info of 2 vms running in cloud
   
    
    static_vms:
      - &vm1
        ip_address: 10.10.10.2
        user_name: ubuntu
        ssh_private_key: /Users/sgangaraju/.ssh/known_hosts
        internal_ip: 172.16.0.2
        install_packages: false
      - &vm2
        ip_address: 10.10.10.1
        user_name: ubuntu
        ssh_private_key: /Users/sgangaraju/.ssh/known_hosts
        internal_ip: 172.16.0.1
        ssh_port: 22

    iperf:
     vm_groups:
      iperf_vm_1:
        static_vms:
           - *vm1
       iperf_vm_2:
         static_vms:
           - *vm2

    benchmarks:
      - iperf:
    
I ran the test using following command

    ./pkb.py --cloud=OpenStack  --benchmarks=iperf --benchmark_config_file=sai_user_config.yaml

2016-01-13 18:46:54,061 24eb6475 MainThread INFO     Verbose logging to: /var/folders/6r/7jjg694x3w9_x9g2x7n7_0pj_m09f4/T/perfkitbenchmarker/run_24eb6475/pkb.log
2016-01-13 18:46:54,062 24eb6475 MainThread INFO     PerfKitBenchmarker version: v1.0.1-134-gface703
2016-01-13 18:46:54,205 24eb6475 MainThread INFO     Flag values:
--benchmark_config_file=sai_user_config.yaml
--cloud=OpenStack
--benchmarks=iperf
2016-01-13 18:46:54,223 24eb6475 MainThread WARNING  The key "iperf_vm_2" was not in the default config, but was in user overrides. This may indicate a typo.
2016-01-13 18:46:54,223 24eb6475 MainThread WARNING  The key "iperf_vm_1" was not in the default config, but was in user overrides. This may indicate a typo.
Traceback (most recent call last):

What step am i missing?Would be great if anyone can help in this

**Comment by meteorfox** [comment]
Ok,

`ssh_private_key` should be the path to the SSH private key that matches the SSH public key you are using for your VM, `known_hosts` is most likely not the private key file. Usually the SSH key pair is generated using `ssh-keygen` and then the public key is uploaded to your cloud.

You probably want to remove `install_package: false` for the first VM spec, since we want to make sure it install the required packages with APT.

There's no need to specify `ssh_port: 22` property, since that is the default. 

There's no need to specify `benchmarks` in your configuration file, if you are using the `--benchmarks=iperf` flag in the `pkb.py` command.

So in summary, your config file should look something like this:

```yaml
static_vms:
  - &vm1
    ip_address: 10.10.10.2
    user_name: ubuntu
    ssh_private_key: /Users/sgangaraju/.ssh/my_secret_key
    internal_ip: 172.16.0.2
  - &vm2
    ip_address: 10.10.10.1
    user_name: ubuntu
    ssh_private_key: /Users/sgangaraju/.ssh/my_secret_key
    internal_ip: 172.16.0.1

iperf:
 vm_groups:
   iperf_vm_1:
      static_vms:
        - *vm1
   iperf_vm_2:
      static_vms:
        - *vm2
```

Also make sure the `ip_address` is reachable from wherever your executing `pkb.py`, otherwise it won't be able to SSH in.

I hope that gets you a little further, let me know if that still doesn't work for you.
