### ISSUE TITLE
Add a way for users to specify global flag values in the YAML file

### ISSUE THREAD

**Issue by skschneider** [GoogleCloudPlatform/PerfKitBenchmarker#814]
I was discussing the YAML config files with @ehankland.

Currently, there's a way to specify flag value overrides per benchmark run. It could be useful to have a way to specify a higher-level flag value override that applies to the entire PKB run.

I assume the priority would be such that the benchmark-specific overrides would take precedence over the global overrides, but because the global flag overrides would still modify the flag values, they would still take precedence over benchmark-specific config options.

Example:

```
flags:
  machine_type: n1-standard-1  # Middle priority

iperf:
  flags:
    machine_type: n1-standard-2 # Highest priority
  vm_groups:
    default:
      GCP:
        machine_type: n1-standard-4 # Lowest priority
```
